# docker-compose.dev.yml
services:
  # --- Application Service ---
  app-dev:
    # container_name: my-awesome-app # ตั้งชื่อเองได้เลย
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - APP_PORT=${APP_PORT}
      - HOST_PORT=${HOST_PORT}
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    networks:
      - app-network # 👈 บอกให้ app-dev เข้าร่วมหมู่บ้าน app-network

  # --- Migrate Service ---
  migrate:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    env_file:
      - .env # 👈 อ่านจาก .env ไฟล์เดียวกัน
    volumes:
      - .:/app
    networks:
      - app-network # 👈 บอกให้ migrate เข้าร่วมหมู่บ้าน app-network
  
  app-debug:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
    ports:
      - "9997:9998" # 👈 ใช้ Port อื่นที่ไม่ซ้ำกับของเดิม
    networks:
      - app-network
    # ⭐️⭐️⭐️ นี่คือหัวใจ! เราจะ override command ⭐️⭐️⭐️
    # สั่งให้มันรันแอปตรงๆ เลย ไม่ต้องผ่าน CompileDaemon
    command: ["go", "run", "./cmd/api/main.go"]

# ⭐️⭐️⭐️ บอก Docker Compose ว่า "หมู่บ้าน" ที่เราจะไปอยู่นั้น
# เป็นหมู่บ้านที่มีอยู่แล้วนะ ไม่ต้องสร้างใหม่!
networks:
  app-network:
    external: true